apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-tls
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "certs/alertmanager.crt" | b64enc }}
  tls.key: {{ .Files.Get "certs/alertmanager.key" | b64enc }}
