apiVersion: v1
kind: Secret
metadata:
  name: grafana-tls
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "certs/grafana.crt" | b64enc }}
  tls.key: {{ .Files.Get "certs/grafana.key" | b64enc }}
