apiVersion: v1
kind: Secret
metadata:
  name: prometheus-tls
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "certs/prometheus.crt" | b64enc }}
  tls.key: {{ .Files.Get "certs/prometheus.key" | b64enc }}
